### ISSUE TITLE
[TestTools]横琴业务员告知报错

### ISSUE THREAD

**Issue by bryan-gu** [eBaoTech/last-hit#1]
录入时完全正常。回访时，输入完所有的信息后点击下一步，光标回到“被保险人收入”，并提示“请正确输入您估计的被保险人收入信息”

![Capture](https://user-images.githubusercontent.com/56816314/67184547-9bb06f80-f416-11e9-9710-4f50093db9b9.PNG)

[HQtest.flow.json.zip](https://github.com/eBaoTech/last-hit/files/3749493/HQtest.flow.json.zip)

**Comment by bryan-gu** [comment]
君康业务员告知也出现问题。

![4512d26c8dd36f6bcf310c72cdd2134](https://user-images.githubusercontent.com/56816314/67266997-07acd980-f4e4-11e9-987f-7491aa357fda.png)

![f1f662156a3d183e18c7414ec2b944f](https://user-images.githubusercontent.com/56816314/67267005-0b406080-f4e4-11e9-91dc-d4eb971d4ed5.png)

[JKxfl.flow.json.zip](https://github.com/eBaoTech/last-hit/files/3754286/JKxfl.flow.json.zip)

**Comment by bradwoo8621** [comment]
HQ我很完美的回放了.
JK这个录制有问题, 重新录个试试呢, 我放到有个select选择就挂了.

**Comment by bryan-gu** [comment]
@bradwoo8621 布叔，君康的这个脚本在lingbin的电脑上很完美的回放了。

**Comment by bradwoo8621** [comment]
赞, 那我关了issue.
