### ISSUE TITLE
[TestTools]电投风险提示语回放报错

### ISSUE THREAD

**Issue by bryan-gu** [eBaoTech/last-hit#10]
电投风险提示语录入正常，回放报错。

![Capture](https://user-images.githubusercontent.com/56816314/67745408-1bfe5280-fa5f-11e9-8450-acb2cc33b7e8.PNG)

[test2.flow.json.zip](https://github.com/eBaoTech/last-hit/files/3782111/test2.flow.json.zip)

**Comment by bradwoo8621** [comment]
别给我 @bryan-gu

**Comment by zhenlong1028** [comment]
测了下，发现step中已跑到下个step，但是浏览器中页面仍停留在上个页面，导致找不到页面元素而报错。

**Comment by zhenlong1028** [comment]
![image](https://user-images.githubusercontent.com/47881479/68584541-d019c780-04ba-11ea-936f-f125ca3510d1.png)
暂时没搞清楚，为什么前面几步都跳转了，39却没有跳转。

**Comment by zhenlong1028** [comment]
clpcp页面跳转路由利用的是#后面的值。
const getUrlPath = url => {
	const parsed = new URL(url);
	parsed.search = '';
	//parsed.hash = '';
	return parsed.href;
};
URL判断时hash需要保留，经过测试发现可以跳转到页面。但是后续step中仍后错误
