### ISSUE TITLE
[TestTools]选择华夏产品进入的是天安的产品

### ISSUE THREAD

**Issue by bryan-gu** [eBaoTech/last-hit#4]
录制时未出现问题，回放时在永达理主页面点击产品，输入华夏，点击查询。搜索出华夏的产品，随意点击一款产品，进入的产品为“天安传世福”（有概率发生）

同样遇到问题的还有百年的这个脚本，搜索百年的产品，点进去是信泰的产品。

[BNtest.flow.json.zip](https://github.com/eBaoTech/last-hit/files/3749609/BNtest.flow.json.zip)

**Comment by bradwoo8621** [comment]
@bryan-gu, 这是搜索顺序问题. 录下来的脚本, 他是点击列表的`第几个`, 比如你录的是点击第一个产品卡, 他是某个产品. 但是回放的时候, 由于列表顺序问题, 第一个就已经未必是你录的时候当时的产品了. 所以进去就错了.

建议是要测产生流程, 你就直接用免登陆测, 不要这么麻烦从真正页面登录开始, 你也不是为了测试前面那些功能对吧.
