### ISSUE TITLE
[TestTools]电投上传影像，回放时会报错

### ISSUE THREAD

**Issue by bryan-gu** [eBaoTech/last-hit#5]
回放至影像上传报错

![image](https://user-images.githubusercontent.com/56816314/67187040-eda7c400-f41b-11e9-800a-f2d59d00382f.png)

**Comment by bradwoo8621** [comment]
@bryan-gu 把日志弄出来, 看上去是报什么目录出错嘛. 我在mac上是好的, 没办法重现这个异常.

**Comment by bryan-gu** [comment]
@bradwoo8621 布叔，这个上传影像回放的问题已经可以通过了，现在回放的时候可以正常回放了。不过签名暂时无法签名，估计是因为无法识别按住鼠标滑动的原因

**Comment by bradwoo8621** [comment]
好, 签名就是跟那个 #2 一样了,  那这个关了.
